#!/bin/bash
docker build -t katello_exporter .
docker images
docker tag katello_exporter $DOCKER_USERNAME/katello_exporter
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
docker push $DOCKER_USERNAME/katello_exporter
